urls.py
from django.conf.urls import url
from django.contrib.auth import views
from .views import (
    PropietarioCreation,
    PropietarioDetail,
    PropietarioList,
    PropietarioUpdate,
    PacienteList,
    PacienteCreation,
    PacienteUpdate,
    PacienteDetail,
    VacunaList,
    VacunaCreation,
    VacunaDetail,
    VacunaUpdate,
    EnfermedadList,
    EnfermedadCreation,
    EnfermedadDetail,
    EnfermedadUpdate,
    AntiparasitarioList,
    AntiparasitarioCreation,
    AntiparasitarioDetail,
    AntiparasitarioUpdate,
    home,
    delete_antiparasitario,
    delete_enfermedad,
    delete_vacuna,
    delete_paciente,
    delete_propietario,
    PropietarioListJson,
    PacienteListJson,
    VacunaListJson,
    EnfermedadListJson,
    AntiparasitarioListJson,
)

app_name = 'animalchic'
urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', views.login, kwargs={'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', views.logout,kwargs={'next_page': '/'}, name='logout'),
    ############ Urls para modelo Propietario ##############################
    url(r'^propietarios/$', PropietarioList.as_view(), name='list_propietarios'),
    url(r'^propietarios_json/$',PropietarioListJson.as_view(), name='list_propietarios_json'),
    url(r'^propietarios/(?P<pk>\d+)/$', PropietarioDetail.as_view(), name='detail_propietario'),
    url(r'^nuevo_propietario/$', PropietarioCreation.as_view(), name='new_propietario'),
    url(r'^editar_propietario/(?P<pk>\d+)/$', PropietarioUpdate.as_view(), name='edit_propietario'),
    url(r'^borrar_propietario/(?P<pk>\d+)/$', delete_propietario, name='delete_propietario'),
    #url(r'^propietarios/(?P<pk_propietario>\d+)/pacientes/$', PacienteList.as_view(), name='list_propietario_pacientes'),
    #url(r'^propietarios/(?P<pk_propietario>\d+)/pacientes_json/$', PacienteListJson.as_view(), name='list_propietario_pacientes_json'),
    url(r'^propietarios/(?P<pk_propietario>\d+)/pacientes/nuevo_paciente/$', PacienteCreation.as_view(),name='nuevo_propietario_paciente'),
    ############ Urls para modelo Paciente ##############################
    url(r'^pacientes/$', PacienteList.as_view(), name='list_pacientes'),
    url(r'^pacientes_json/$', PacienteListJson.as_view(), name='list_pacientes_json'),
    url(r'^pacientes/(?P<pk>\d+)/$', PacienteDetail.as_view(), name='detail_paciente'),
    url(r'^nuevo_paciente/$', PacienteCreation.as_view(), name='new_paciente'),
    url(r'^editar_paciente/(?P<pk>\d+)/$', PacienteUpdate.as_view(), name='edit_paciente'),
    url(r'^borrar_paciente/(?P<pk>\d+)/$', delete_paciente, name='delete_paciente'),
    ############ Urls para modelo Vacuna ##############################
    url(r'^pacientes/(?P<pk_paciente>\d+)/vacunas/$', VacunaList.as_view() , name='list_vacunas'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/vacunas_json/$', VacunaListJson.as_view(), name='list_vacunas_json'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/vacunas/(?P<pk_vacuna>\d+)/$', VacunaDetail.as_view(), name='detail_vacuna'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/nueva_vacuna/$', VacunaCreation.as_view(), name='new_vacuna'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/editar_vacuna/(?P<pk_vacuna>\d+)/$', VacunaUpdate.as_view(), name='edit_vacuna'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/borrar_vacuna/(?P<pk_vacuna>\d+)/$', delete_vacuna, name='delete_vacuna'),
    ############ Urls para modelo Enfermedad ##############################
    url(r'^pacientes/(?P<pk_paciente>\d+)/enfermedades/$', EnfermedadList.as_view() , name='list_enfermedades'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/enfermedades_json/$', EnfermedadListJson.as_view() , name='list_enfermedades_json'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/enfermedades/(?P<pk_enfermedad>\d+)/$', EnfermedadDetail.as_view(), name='detail_enfermedad'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/nueva_enfermedad/$', EnfermedadCreation.as_view(), name='new_enfermedad'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/editar_enfermedad/(?P<pk_enfermedad>\d+)/$', EnfermedadUpdate.as_view(), name='edit_enfermedad'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/borrar_enfermedad/(?P<pk_enfermedad>\d+)/$', delete_enfermedad, name='delete_enfermedad'),
    ############ Urls para modelo Antiparasitario ##########################
    url(r'^pacientes/(?P<pk_paciente>\d+)/antiparasitarios/$', AntiparasitarioList.as_view() , name='list_antiparasitarios'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/antiparasitarios_json/$', AntiparasitarioListJson.as_view() , name='list_antiparasitarios_json'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/antiparasitarios/(?P<pk_antiparasitario>\d+)/$', AntiparasitarioDetail.as_view(), name='detail_antiparasitario'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/nuevo_antiparasitario/$', AntiparasitarioCreation.as_view(), name='new_antiparasitario'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/editar_antiparasitario/(?P<pk_antiparasitario>\d+)/$', AntiparasitarioUpdate.as_view(), name='edit_antiparasitario'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/borrar_antiparasitario/(?P<pk_antiparasitario>\d+)/$', delete_antiparasitario, name='delete_antiparasitario'),
]

templates/animalchic/listing/antiparasitario_list.html
{% extends 'animalchic/index.html' %}

{% load i18n staticfiles %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
    <script src="{% static "js/datatable_function.js" %}"></script>
    <script type="text/javascript">
        var USERS_LIST_JSON_URL = "{% url 'animalchic:list_antiparasitarios_json' paciente_id %}";
        // translations for datatables

        var dt_language = {
            "emptyTable":     "{% trans "No hay datos disponibles" %}",
            "info":           "{% trans "Mostrando _START_ a _END_ de _TOTAL_ entradas" %}",
            "infoEmpty":      "{% trans "Mostrando 0 a 0 de 0 entradas" %}",
            "infoFiltered":   "{% trans "(filtrando de _MAX_ del total de entradas)" %}",
            "infoPostFix":    "",
            "thousands":      ",",
            "lengthMenu":     "{% trans "Mostrando _MENU_ entradas" %}",
            "loadingRecords": "{% trans "Cargando..." %}",
            "processing":     "{% trans "Procesando..." %}",
            "search":         "{% trans "Buscar:" %}",
            "zeroRecords":    "{% trans "No se han encontrado registros" %}",
            "paginate": {
                "first":      "{% trans "Primero" %}",
                "last":       "{% trans "Ultimo" %}",
                "next":       "{% trans "Siguiente" %}",
                "previous":   "{% trans "Previo" %}"
            },
            "aria": {
                "sortAscending":  "{% trans ": activar el ordenamiento de columnas ascendentes" %}",
                "sortDescending": "{% trans ": activar el ordenamiento de columnas descendentes" %}"
            }
        }
    </script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-8">
                <h2>Antiparasitarios</h2>
                <h2>Paciente: <i>{{paciente_nombre}}</i></h2>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-hover datatable">
                <thead>
                    <tr class="active">
                        <th>Vermifugos</th>
                        <th>Fecha</th>
                        <th>Proxima Aplicacion</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>

                </tfoot>
{#                {% for antiparasitario in object_list %}#}
{#                <tr data-href="{% url 'animalchic:detail_antiparasitario' paciente_id antiparasitario.id %}">#}
{#                    <th>{{antiparasitario.vermifugos}}</th>#}
{#                    <th>{{antiparasitario.fecha}}</th>#}
{#                    <th>{{antiparasitario.proxima_aplicacion}}</th>#}
{#                </tr>#}
{#                {% endfor %}#}
            </table>
            <a href="{% url 'animalchic:detail_paciente' paciente_id %}" class="btn btn-primary">Regresar</a>
            <a class="btn btn-success" href="{% url 'animalchic:new_antiparasitario' paciente_id %}">Agregar Antiparasitario</a>
        </div>
    </div>
</div>
{% endblock %}

templates/animalchic/listing/enfermedad_list.html
{% extends 'animalchic/index.html' %}

{% load i18n staticfiles %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
    <script src="{% static "js/datatable_function.js" %}"></script>
    <script type="text/javascript">
        var USERS_LIST_JSON_URL = "{% url 'animalchic:list_enfermedades_json' paciente_id %}";
        // translations for datatables

        var dt_language = {
            "emptyTable":     "{% trans "No hay datos disponibles" %}",
            "info":           "{% trans "Mostrando _START_ a _END_ de _TOTAL_ entradas" %}",
            "infoEmpty":      "{% trans "Mostrando 0 a 0 de 0 entradas" %}",
            "infoFiltered":   "{% trans "(filtrando de _MAX_ del total de entradas)" %}",
            "infoPostFix":    "",
            "thousands":      ",",
            "lengthMenu":     "{% trans "Mostrando _MENU_ entradas" %}",
            "loadingRecords": "{% trans "Cargando..." %}",
            "processing":     "{% trans "Procesando..." %}",
            "search":         "{% trans "Buscar:" %}",
            "zeroRecords":    "{% trans "No se han encontrado registros" %}",
            "paginate": {
                "first":      "{% trans "Primero" %}",
                "last":       "{% trans "Ultimo" %}",
                "next":       "{% trans "Siguiente" %}",
                "previous":   "{% trans "Previo" %}"
            },
            "aria": {
                "sortAscending":  "{% trans ": activar el ordenamiento de columnas ascendentes" %}",
                "sortDescending": "{% trans ": activar el ordenamiento de columnas descendentes" %}"
            }
        }
    </script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-8">
                <h2>Enfermedades</h2>
                <h2>Paciente: <i>{{paciente_nombre}}</i></h2>

            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-hover datatable">
                <thead>
                    <tr class="active">
                        <th>Descripcion</th>
                        <th>Fecha</th>
                        <th>Proxima Vacuna</th>
                        <th></th>
                    </tr>
                </thead>
                <tfoot>

                </tfoot>
{#                {% for enfermedad in object_list %}#}
{#                <tr data-href="{% url 'animalchic:detail_enfermedad' paciente_id enfermedad.id %}">#}
{#                    <th>{{enfermedad.descripcion}}</th>#}
{#                    <th>{{enfermedad.fecha}}</th>#}
{#                    <th>{{enfermedad.tratamiento}}</th>#}
{#                </tr>#}
{#                {% endfor %}#}
            </table>
            <a href="{% url 'animalchic:detail_paciente' paciente_id %}" class="btn btn-primary">Regresar</a>
            <a class="btn btn-success" href="{% url 'animalchic:new_enfermedad' paciente_id %}">Agregar Enfermedad</a>
        </div>
    </div>
</div>
{% endblock %}

templates/animalchic/listing/paciente_list.html
{% extends 'animalchic/index.html'%}

{% load i18n staticfiles %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
    <script src="{% static "js/datatable_function.js" %}"></script>
    <script type="text/javascript">
        var USERS_LIST_JSON_URL = "{% url 'animalchic:list_pacientes_json' %}";
        // translations for datatables

        var dt_language = {
            "emptyTable":     "{% trans "No hay datos disponibles" %}",
            "info":           "{% trans "Mostrando _START_ a _END_ de _TOTAL_ entradas" %}",
            "infoEmpty":      "{% trans "Mostrando 0 a 0 de 0 entradas" %}",
            "infoFiltered":   "{% trans "(filtrando de _MAX_ del total de entradas)" %}",
            "infoPostFix":    "",
            "thousands":      ",",
            "lengthMenu":     "{% trans "Mostrando _MENU_ entradas" %}",
            "loadingRecords": "{% trans "Cargando..." %}",
            "processing":     "{% trans "Procesando..." %}",
            "search":         "{% trans "Buscar:" %}",
            "zeroRecords":    "{% trans "No se han encontrado registros" %}",
            "paginate": {
                "first":      "{% trans "Primero" %}",
                "last":       "{% trans "Ultimo" %}",
                "next":       "{% trans "Siguiente" %}",
                "previous":   "{% trans "Previo" %}"
            },
            "aria": {
                "sortAscending":  "{% trans ": activar el ordenamiento de columnas ascendentes" %}",
                "sortDescending": "{% trans ": activar el ordenamiento de columnas descendentes" %}"
            }
        }
    </script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-8">
                <h2>Pacientes</h2>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-hover datatable display">
                <thead>
                    <tr class="active">
                    <th>Propietario</th>
                    <th>Nombre</th>
                    <th>Especie</th>
                    <th>Raza</th>
                    <th>Sexo</th>
                    <th></th>
                </tr>
                </thead>
                    <tfoot>
{#                        {% for row in data.rows %}#}
{#                            <tr data-href="{% url 'animalchic:detail_paciente'  %}">#}
{#                                <th>Propietario</th>#}
{#                                <th>Nombre</th>#}
{#                                <th>Especie</th>#}
{#                                <th>Raza</th>#}
{#                                <th>Sexo del animal</th>#}
{#                                <th>show</th>#}
{#                            </tr>#}
{#                        {% endfor %}#}
                    </tfoot>
            </table>
            {% if nuevo_propietario_paciente %}
                <a class="btn btn-success" href="{% url 'animalchic:nuevo_propietario_paciente' propietario_id %}">Agregar Paciente</a>
            {% else %}
                <a class="btn btn-success" href="{% url 'animalchic:new_paciente' %}">Agregar Paciente</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

templates/animalchic/listing/propietario_list.html
{% extends 'animalchic/index.html' %}

{% load i18n staticfiles %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
    <script src="{% static "js/datatable_function.js" %}"></script>
    <script type="text/javascript">
        var USERS_LIST_JSON_URL = "{% url 'animalchic:list_propietarios_json' %}";
        // translations for datatables

        var dt_language = {
            "emptyTable":     "{% trans "No hay datos disponibles" %}",
            "info":           "{% trans "Mostrando _START_ a _END_ de _TOTAL_ entradas" %}",
            "infoEmpty":      "{% trans "Mostrando 0 a 0 de 0 entradas" %}",
            "infoFiltered":   "{% trans "(filtrando de _MAX_ del total de entradas)" %}",
            "infoPostFix":    "",
            "thousands":      ",",
            "lengthMenu":     "{% trans "Mostrando _MENU_ entradas" %}",
            "loadingRecords": "{% trans "Cargando..." %}",
            "processing":     "{% trans "Procesando..." %}",
            "search":         "{% trans "Buscar:" %}",
            "zeroRecords":    "{% trans "No se han encontrado registros" %}",
            "paginate": {
                "first":      "{% trans "Primero" %}",
                "last":       "{% trans "Ultimo" %}",
                "next":       "{% trans "Siguiente" %}",
                "previous":   "{% trans "Previo" %}"
            },
            "aria": {
                "sortAscending":  "{% trans ": activar el ordenamiento de columnas ascendentes" %}",
                "sortDescending": "{% trans ": activar el ordenamiento de columnas descendentes" %}"
            }
        }
    </script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-4">
                <h2>Propietarios</h2>
            </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">

                <table class="datatable">
                    <thead>
                        <th> {% trans "Nombre" %}</th>
                        <th> {% trans "Direccion" %}</th>
                        <th> {% trans "Telefono" %}</th>
                        <th> {% trans "Observacion" %}</th>
                        <th></th>
                    </thead>
                    <tbody>
{#                        {% for row in instances %}#}
{#                            <tr>#}
{#                                <th>{{ row.propietario_nombre }}</th>#}
{#                                <th>{{ row.direccion }}</th>#}
{#                                <th>{{ row.telefono }}</th>#}
{#                                <th>{{ row.observacion }}</th>#}
{#                            </tr>#}
{#                        {% endfor %}#}
                    </tbody>
                </table>

                <a class="btn btn-success" href="{% url 'animalchic:new_propietario' %}">Agregar Propietario</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/animalchic/listing/vacuna_list.html
{% extends 'animalchic/index.html' %}

{% load i18n staticfiles %}

{% block extra_head %}
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.12/css/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.12/js/jquery.dataTables.js"></script>
    <script src="{% static "js/datatable_function.js" %}"></script>
    <script type="text/javascript">
        var USERS_LIST_JSON_URL = "{% url 'animalchic:list_vacunas_json' paciente_id %}";
        // translations for datatables

        var dt_language = {
            "emptyTable":     "{% trans "No hay datos disponibles" %}",
            "info":           "{% trans "Mostrando _START_ a _END_ de _TOTAL_ entradas" %}",
            "infoEmpty":      "{% trans "Mostrando 0 a 0 de 0 entradas" %}",
            "infoFiltered":   "{% trans "(filtrando de _MAX_ del total de entradas)" %}",
            "infoPostFix":    "",
            "thousands":      ",",
            "lengthMenu":     "{% trans "Mostrando _MENU_ entradas" %}",
            "loadingRecords": "{% trans "Cargando..." %}",
            "processing":     "{% trans "Procesando..." %}",
            "search":         "{% trans "Buscar:" %}",
            "zeroRecords":    "{% trans "No se han encontrado registros" %}",
            "paginate": {
                "first":      "{% trans "Primero" %}",
                "last":       "{% trans "Ultimo" %}",
                "next":       "{% trans "Siguiente" %}",
                "previous":   "{% trans "Previo" %}"
            },
            "aria": {
                "sortAscending":  "{% trans ": activar el ordenamiento de columnas ascendentes" %}",
                "sortDescending": "{% trans ": activar el ordenamiento de columnas descendentes" %}"
            }
        }
    </script>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-8">
                <h2>Vacunas</h2>
                <h2>Paciente: <i>{{paciente_nombre}}</i></h2>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-hover datatable">
                <thead>
                    <tr class="active">
                        <th>Descripcion</th>
                        <th>Fecha</th>
                        <th>Proxima Vacuna</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
{#                {% for vacuna in object_list %}#}
{#                <tr data-href="{% url 'animalchic:detail_vacuna' paciente_id vacuna.id %}">#}
{#                    <th>{{vacuna.descripcion}}</th>#}
{#                    <th>{{vacuna.fecha}}</th>#}
{#                    <th>{{vacuna.proxima_vacuna}}</th>#}
{#                    <th></th>#}
{#                    <th></th>#}
{#                </tr>#}
{##}
{#                {% endfor %}#}
            </table>
            <a href="{% url 'animalchic:detail_paciente' paciente_id %}" class="btn btn-primary">Regresar</a>
            <a class="btn btn-success" href="{% url 'animalchic:new_vacuna' paciente_id %}">Agregar Vacuna</a>
        </div>
    </div>
</div>
{% endblock %}