urls.py
from django.conf.urls import url
from django.contrib.auth import views
from .views import (
    PropietarioCreation,
    PropietarioDetail,
    PropietarioList,
    PropietarioUpdate,
    PacienteList,
    PacienteCreation,
    PacienteUpdate,
    PacienteDetail,
    VacunaList,
    VacunaCreation,
    VacunaDetail,
    VacunaUpdate,
    EnfermedadList,
    EnfermedadCreation,
    EnfermedadDetail,
    EnfermedadUpdate,
    AntiparasitarioList,
    AntiparasitarioCreation,
    AntiparasitarioDetail,
    AntiparasitarioUpdate,
    home,
    delete_antiparasitario,
    delete_enfermedad,
    delete_vacuna,
    delete_paciente,
    delete_propietario,
    PropietarioListJson,
    PacienteListJson,
    VacunaListJson,
    EnfermedadListJson,
    AntiparasitarioListJson,
)

app_name = 'animalchic'
urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', views.login, kwargs={'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', views.logout,kwargs={'next_page': '/'}, name='logout'),
    ############ Urls para modelo Propietario ##############################
    url(r'^propietarios/$', PropietarioList.as_view(), name='list_propietarios'),
    url(r'^propietarios_json/$',PropietarioListJson.as_view(), name='list_propietarios_json'),
    url(r'^propietarios/(?P<pk>\d+)/$', PropietarioDetail.as_view(), name='detail_propietario'),
    url(r'^nuevo_propietario/$', PropietarioCreation.as_view(), name='new_propietario'),
    url(r'^editar_propietario/(?P<pk>\d+)/$', PropietarioUpdate.as_view(), name='edit_propietario'),
    url(r'^borrar_propietario/(?P<pk>\d+)/$', delete_propietario, name='delete_propietario'),
    #url(r'^propietarios/(?P<pk_propietario>\d+)/pacientes/$', PacienteList.as_view(), name='list_propietario_pacientes'),
    #url(r'^propietarios/(?P<pk_propietario>\d+)/pacientes_json/$', PacienteListJson.as_view(), name='list_propietario_pacientes_json'),
    url(r'^propietarios/(?P<pk_propietario>\d+)/pacientes/nuevo_paciente/$', PacienteCreation.as_view(),name='nuevo_propietario_paciente'),
    ############ Urls para modelo Paciente ##############################
    url(r'^pacientes/$', PacienteList.as_view(), name='list_pacientes'),
    url(r'^pacientes_json/$', PacienteListJson.as_view(), name='list_pacientes_json'),
    url(r'^pacientes/(?P<pk>\d+)/$', PacienteDetail.as_view(), name='detail_paciente'),
    url(r'^nuevo_paciente/$', PacienteCreation.as_view(), name='new_paciente'),
    url(r'^editar_paciente/(?P<pk>\d+)/$', PacienteUpdate.as_view(), name='edit_paciente'),
    url(r'^borrar_paciente/(?P<pk>\d+)/$', delete_paciente, name='delete_paciente'),
    ############ Urls para modelo Vacuna ##############################
    url(r'^pacientes/(?P<pk_paciente>\d+)/vacunas/$', VacunaList.as_view() , name='list_vacunas'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/vacunas_json/$', VacunaListJson.as_view(), name='list_vacunas_json'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/vacunas/(?P<pk_vacuna>\d+)/$', VacunaDetail.as_view(), name='detail_vacuna'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/nueva_vacuna/$', VacunaCreation.as_view(), name='new_vacuna'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/editar_vacuna/(?P<pk_vacuna>\d+)/$', VacunaUpdate.as_view(), name='edit_vacuna'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/borrar_vacuna/(?P<pk_vacuna>\d+)/$', delete_vacuna, name='delete_vacuna'),
    ############ Urls para modelo Enfermedad ##############################
    url(r'^pacientes/(?P<pk_paciente>\d+)/enfermedades/$', EnfermedadList.as_view() , name='list_enfermedades'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/enfermedades_json/$', EnfermedadListJson.as_view() , name='list_enfermedades_json'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/enfermedades/(?P<pk_enfermedad>\d+)/$', EnfermedadDetail.as_view(), name='detail_enfermedad'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/nueva_enfermedad/$', EnfermedadCreation.as_view(), name='new_enfermedad'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/editar_enfermedad/(?P<pk_enfermedad>\d+)/$', EnfermedadUpdate.as_view(), name='edit_enfermedad'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/borrar_enfermedad/(?P<pk_enfermedad>\d+)/$', delete_enfermedad, name='delete_enfermedad'),
    ############ Urls para modelo Antiparasitario ##########################
    url(r'^pacientes/(?P<pk_paciente>\d+)/antiparasitarios/$', AntiparasitarioList.as_view() , name='list_antiparasitarios'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/antiparasitarios_json/$', AntiparasitarioListJson.as_view() , name='list_antiparasitarios_json'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/antiparasitarios/(?P<pk_antiparasitario>\d+)/$', AntiparasitarioDetail.as_view(), name='detail_antiparasitario'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/nuevo_antiparasitario/$', AntiparasitarioCreation.as_view(), name='new_antiparasitario'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/editar_antiparasitario/(?P<pk_antiparasitario>\d+)/$', AntiparasitarioUpdate.as_view(), name='edit_antiparasitario'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/borrar_antiparasitario/(?P<pk_antiparasitario>\d+)/$', delete_antiparasitario, name='delete_antiparasitario'),
]

templates/animalchic/index.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="UTF-8">
    <title>Animal Chic</title>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimun-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="http://cdn.bootcss.com/twitter-bootstrap/3.0.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
    <script src="http://cdn.bootcss.com/twitter-bootstrap/3.0.2/js/bootstrap.min.js"></script>

    <script src="http://ajax.aspnetcdn.com/ajax/jquery/jquery-1.9.0.js"></script>
    {% block extra_head %}{% endblock %}

</head>
<body>
    <div class="container">
      <br>
      <header>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapsed" data-target="#navbar-1">
                <span class="sr-only">Menu</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
                <img href="#" class="navbar-brand" src="{% static 'images/animalchic-logo.png' %}" width="100" >
            </div>

            <div class="navbar-collapse collapse" id="#navbar-1">
              <ul class="nav navbar-nav">
                  <li><a class="" href="{% url 'animalchic:list_propietarios' %}">Propietarios</a></li>
                  <li><a class="" href="{% url 'animalchic:list_pacientes' %}">Pacientes</a></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                 <li class="dropdown">
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.get_username }}<span class="caret"></span></a>
                     <ul class="dropdown-menu">
{#                         <li><a href="#">Configuraciones</a></li>#}
                        <li><a href="{% url 'animalchic:logout' %}">Salir</a></li>
                     </ul>
                 </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
      </header>
    </div>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>

    <script src="{% static 'js/table_handle.js' %}"></script>
{#    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>#}
{#    <script src="{% static 'js/jquery.min.js' %}"></script>#}


    <!-- Include Date Range Picker -->
    {<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>

    <script>
    $(document).ready(function() {
        $('.datepicker').datepicker();
    });
    $('tr[data-href]').on("click", function() {
        document.location = $(this).data('href');
    });
    $('#confirm-delete').on('show.bs.modal', function(e) {
        $(this).find('.btn-ok').attr('href', $(e.relatedTarget).data('href'));
    });
    </script>
</body>
</html>

templates/animalchic/main.html
{% extends 'animalchic/index.html'%}
{% load staticfiles %}

{% block content %}

<div class="row">
    <div class="col-md-6">
            <a href="{% url 'animalchic:list_propietarios' %}">
                <img class="img-responsive center-block" src="{% static 'img/tap.png' %}">
                <h3 class="text-center">Propietarios</h3>
            </a>
    </div>
    <div class="col-md-6">
        <div class="col-md-12 col-centered">
            <a href="{% url 'animalchic:list_pacientes' %}">
                <img class="img-responsive center-block" src="{% static 'img/bone.png' %}">
                <h3 class="text-center">Pacientes</h3>
            </a>
        </div>
    </div>
</div>

{% endblock %}