urls.py
from django.conf.urls import url
from django.contrib.auth import views
from .views import (
    PropietarioCreation,
    PropietarioDetail,
    PropietarioList,
    PropietarioUpdate,
    PacienteList,
    PacienteCreation,
    PacienteUpdate,
    PacienteDetail,
    VacunaList,
    VacunaCreation,
    VacunaDetail,
    VacunaUpdate,
    EnfermedadList,
    EnfermedadCreation,
    EnfermedadDetail,
    EnfermedadUpdate,
    AntiparasitarioList,
    AntiparasitarioCreation,
    AntiparasitarioDetail,
    AntiparasitarioUpdate,
    home,
    delete_antiparasitario,
    delete_enfermedad,
    delete_vacuna,
    delete_paciente,
    delete_propietario,
    PropietarioListJson,
    PacienteListJson,
    VacunaListJson,
    EnfermedadListJson,
    AntiparasitarioListJson,
)

app_name = 'animalchic'
urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^login/$', views.login, kwargs={'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', views.logout,kwargs={'next_page': '/'}, name='logout'),
    ############ Urls para modelo Propietario ##############################
    url(r'^propietarios/$', PropietarioList.as_view(), name='list_propietarios'),
    url(r'^propietarios_json/$',PropietarioListJson.as_view(), name='list_propietarios_json'),
    url(r'^propietarios/(?P<pk>\d+)/$', PropietarioDetail.as_view(), name='detail_propietario'),
    url(r'^nuevo_propietario/$', PropietarioCreation.as_view(), name='new_propietario'),
    url(r'^editar_propietario/(?P<pk>\d+)/$', PropietarioUpdate.as_view(), name='edit_propietario'),
    url(r'^borrar_propietario/(?P<pk>\d+)/$', delete_propietario, name='delete_propietario'),
    #url(r'^propietarios/(?P<pk_propietario>\d+)/pacientes/$', PacienteList.as_view(), name='list_propietario_pacientes'),
    #url(r'^propietarios/(?P<pk_propietario>\d+)/pacientes_json/$', PacienteListJson.as_view(), name='list_propietario_pacientes_json'),
    url(r'^propietarios/(?P<pk_propietario>\d+)/pacientes/nuevo_paciente/$', PacienteCreation.as_view(),name='nuevo_propietario_paciente'),
    ############ Urls para modelo Paciente ##############################
    url(r'^pacientes/$', PacienteList.as_view(), name='list_pacientes'),
    url(r'^pacientes_json/$', PacienteListJson.as_view(), name='list_pacientes_json'),
    url(r'^pacientes/(?P<pk>\d+)/$', PacienteDetail.as_view(), name='detail_paciente'),
    url(r'^nuevo_paciente/$', PacienteCreation.as_view(), name='new_paciente'),
    url(r'^editar_paciente/(?P<pk>\d+)/$', PacienteUpdate.as_view(), name='edit_paciente'),
    url(r'^borrar_paciente/(?P<pk>\d+)/$', delete_paciente, name='delete_paciente'),
    ############ Urls para modelo Vacuna ##############################
    url(r'^pacientes/(?P<pk_paciente>\d+)/vacunas/$', VacunaList.as_view() , name='list_vacunas'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/vacunas_json/$', VacunaListJson.as_view(), name='list_vacunas_json'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/vacunas/(?P<pk_vacuna>\d+)/$', VacunaDetail.as_view(), name='detail_vacuna'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/nueva_vacuna/$', VacunaCreation.as_view(), name='new_vacuna'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/editar_vacuna/(?P<pk_vacuna>\d+)/$', VacunaUpdate.as_view(), name='edit_vacuna'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/borrar_vacuna/(?P<pk_vacuna>\d+)/$', delete_vacuna, name='delete_vacuna'),
    ############ Urls para modelo Enfermedad ##############################
    url(r'^pacientes/(?P<pk_paciente>\d+)/enfermedades/$', EnfermedadList.as_view() , name='list_enfermedades'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/enfermedades_json/$', EnfermedadListJson.as_view() , name='list_enfermedades_json'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/enfermedades/(?P<pk_enfermedad>\d+)/$', EnfermedadDetail.as_view(), name='detail_enfermedad'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/nueva_enfermedad/$', EnfermedadCreation.as_view(), name='new_enfermedad'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/editar_enfermedad/(?P<pk_enfermedad>\d+)/$', EnfermedadUpdate.as_view(), name='edit_enfermedad'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/borrar_enfermedad/(?P<pk_enfermedad>\d+)/$', delete_enfermedad, name='delete_enfermedad'),
    ############ Urls para modelo Antiparasitario ##########################
    url(r'^pacientes/(?P<pk_paciente>\d+)/antiparasitarios/$', AntiparasitarioList.as_view() , name='list_antiparasitarios'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/antiparasitarios_json/$', AntiparasitarioListJson.as_view() , name='list_antiparasitarios_json'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/antiparasitarios/(?P<pk_antiparasitario>\d+)/$', AntiparasitarioDetail.as_view(), name='detail_antiparasitario'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/nuevo_antiparasitario/$', AntiparasitarioCreation.as_view(), name='new_antiparasitario'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/editar_antiparasitario/(?P<pk_antiparasitario>\d+)/$', AntiparasitarioUpdate.as_view(), name='edit_antiparasitario'),
    url(r'^pacientes/(?P<pk_paciente>\d+)/borrar_antiparasitario/(?P<pk_antiparasitario>\d+)/$', delete_antiparasitario, name='delete_antiparasitario'),
]

templates/animalchic/details/antiparasitario_detail.html
{% extends 'animalchic/index.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6 col-centered">
            <table class="table table-hover">
                <thead class="table-head">
                    <tr>
                        <td><h1>{{ antiparasitario.vermifugos }}</h1></td>
                    </tr>
                </thead>
                <tbody class="table-body">
                    <tr>
                        <td>Paciente</td>
                        <td><i>{{ antiparasitario.paciente.paciente_nombre }}</i></td>
                    </tr>
                    <tr>
                        <td>Fecha</td>
                        <td><i>{{ antiparasitario.fecha }}</i></td>
                    </tr>
                    <tr>
                        <td>Proxima Aplicacion</td>
                        <td><i>{{ antiparasitario.proxima_aplicacion}}</i></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-centered">
            <a class="btn btn-primary" href="{% url 'animalchic:list_antiparasitarios' paciente_id %}">Regresar</a>
            <a href="{% url 'animalchic:edit_antiparasitario' paciente_id antiparasitario.id %}" class="btn btn-primary">Editar</a>
            <a class="btn btn-danger" data-toggle="modal" data-target="#confirm-delete">Eliminar</a>
        </div>
    </div>
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Confirmar Eliminacion</h2>
                </div>
                <form method="post">{% csrf_token %}
                    <div class="modal-body">
                        ¿Estás seguro que deseas borrar el antiparasitario "{{ antiparasitario.vermifugos }}"?
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'animalchic:delete_antiparasitario' paciente_id antiparasitario.id %}" class="btn btn-danger btn-ok">Si</a>
                </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/animalchic/details/enfermedad_detail.html
{% extends 'animalchic/index.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6 col-centered">
            <table class="table table-hover">
                <thead class="table-head">
                    <tr>
                        <td><h2>{{ enfermedad.descripcion }}</h2></td>
                    </tr>
                </thead>
                <tbody class="table-body">
                    <tr>
                        <td>Paciente</td>
                        <td><i>{{ enfermedad.paciente.paciente_nombre }}</i></td>
                    </tr>
                    <tr>
                        <td>Fecha</td>
                        <td><i>{{ enfermedad.fecha }}</i></td>
                    </tr>
                    <tr>
                        <td>Tratamiento</td>
                        <td><i>{{ enfermedad.tratamiento }}</i></td>
                    </tr>
                    <tr>
                        <td>Documento adjunto</td>
                        {% if enfermedad.enfermedad_archivo.name != ''%}
                            <td> <a href="{{enfermedad.enfermedad_archivo.url}}">{{enfermedad.enfermedad_archivo.name}}</a></td>
                        {% else %}
                            <td>No disponible</td>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-centered">
            <a class="btn btn-primary" href="{% url 'animalchic:list_enfermedades' paciente_id %}">Regresar</a>
            <a href="{% url 'animalchic:edit_enfermedad' paciente_id enfermedad.id %}" class="btn btn-primary">Editar</a>
            <a data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger">Eliminar</a>
        </div>
    </div>
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Confirmar Eliminacion</h2>
                </div>
                <form method="post">{% csrf_token %}
                    <div class="modal-body">
                        ¿Estás seguro que deseas borrar la enfermedad "{{ enfermedad.descripcion }}"?
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'animalchic:delete_enfermedad' paciente_id enfermedad.id %}" class="btn btn-danger btn-ok">Si</a>
                </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/animalchic/details/paciente_detail.html
{% extends 'animalchic/index.html' %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-6">
                    <div class="row"><h1>{{paciente.paciente_nombre }}</h1></div><br>
                    <div class="row"><a role="button" class="btn btn-info " href="{% url 'animalchic:list_vacunas' paciente.id %}">Vacunas</a></div><br>
                    <div class="row"><a role="button" class="btn btn-info " href="{% url 'animalchic:list_enfermedades' paciente.id %}">Enfermedades</a></div><br>
                    <div class="row"><a role="button" class="btn btn-info " href="{% url 'animalchic:list_antiparasitarios' paciente.id %}">Antiparasitarios</a></div><br>
                </div>
                <div class="col-md-6">
                    {% if paciente.foto.name != '' %}
                        <img src="{{ paciente.foto.url }}" class="img-rounded img-responsive" >
                    {% else %}
                        <p>No hay foto</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <table class="table table-hover">
                <thead class="table-head">
                    <tr>
                        <td></td>
                        <td></td>
                    </tr>
                </thead>
                <tbody class="table-body">
                    <tr>
                        <td><b>Propietario</b></td>
                        <td><i>{{ paciente.propietario.propietario_nombre }}</i></td>
                    </tr>
                    <tr>
                        <td><b>Especie</b></td>
                        <td><i>{{ paciente.especie }}</i></td>
                    </tr>
                    <tr>
                        <td><b>Raza</b></td>
                        <td><i>{{ paciente.raza }}</i></td>
                    </tr>
                    <tr>
                        <td><b>Sexo</b></td>
                        <td><i>{{ paciente.sexo }}</i></td>
                    </tr>
                    <tr>
                        <td><b>Edad</b></td>
                        <td><i>{{ paciente.get_edad }}</i></td>
                    </tr>
                    <tr>
                        <td><b>Pelaje</b></td>
                        <td><i>{{ paciente.pelaje }}</i></td>
                    </tr>
                </tbody>

            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 col-centered">
            <a role="button" class="btn btn-primary float-right" href="{% url 'animalchic:list_pacientes' %}">Regresar</a>
            <a href="{% url 'animalchic:edit_paciente' paciente.id %}" class="btn btn-primary">Editar</a>
            <a data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger">Eliminar</a>
        </div>
    </div>
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Confirmar Eliminacion</h2>
                </div>
                <form method="post">{% csrf_token %}
                    <div class="modal-body">
                        ¿Estás seguro que deseas borrar el paciente "{{ paciente.paciente_nombre }}"?
                        <b>Se eliminaran las Vacunas, Enfermedades y Antiparasitarios registrados</b>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'animalchic:delete_paciente' paciente.id %}" class="btn btn-danger btn-ok">Si</a>
                </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/animalchic/details/propietario_detail.html
{% extends 'animalchic/index.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-6 col-centered">
            <table class="table table-hover">
                <thead class="table-head">
                    <tr>
                        <td><h1>{{ propietario.propietario_nombre }}</h1></td>
                    </tr>
                </thead>
                <tbody class="table-body">
                    <tr>
                        <td>Direccion</td>
                        <td><i>{{ propietario.direccion }}</i></td>
                    </tr>
                    <tr>
                        <td>Telefono</td>
                        <td><i>{{ propietario.telefono }}</i></td>
                    </tr>
                    <tr>
                        <td>Observacion</td>
                        <td><i>{{ propietario.observacion }}</i></td>
                    </tr>
                </tbody>
            </table>
            <p>

            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-centered">
            <a class="btn btn-primary" href="{% url 'animalchic:list_propietarios' %}">Regresar</a>
            <a href="{% url 'animalchic:edit_propietario' propietario.id %}" class="btn btn-primary">Editar</a>
            <a data-toggle="modal" data-target="#confirm-delete" class="btn btn-danger">Eliminar</a>
{#            <a class="btn btn-info" href="{% url 'animalchic:list_propietario_pacientes' propietario.id%}">Pacientes</a>#}
        </div>
    </div>
    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Confirmar Eliminacion</h2>
                </div>
                <form method="post">{% csrf_token %}
                    <div class="modal-body">
                        ¿Estás seguro que deseas borrar el propietario "{{ propietario.propietario_nombre }}"?
                        <b>Se eliminaran todos los pacientes asociado a el</b>
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        <a href="{% url 'animalchic:delete_propietario' propietario.id %}" class="btn btn-danger btn-ok">Si</a>
                </div>
                </form>
            </div>
        </div>
    </div>
{% endblock%}

templates/animalchic/details/vacuna_detail.html
{% extends 'animalchic/index.html' %}

{% block content %}
<div class="row">
    <div class="col-md-6 col-centered">
        <table class="table table-hover">
            <thead class="table-head">
                <tr>
                    <td><h1>{{ vacuna.descripcion }}</h1></td>
                </tr>
            </thead>
            <tbody class="table-body">
                <tr>
                    <td>Paciente</td>
                    <td><i>{{ vacuna.paciente.paciente_nombre }}</i></td>
                </tr>
            <tr>
                <td>Fecha</td>
                <td><i>{{ vacuna.fecha }}</i></td>
            </tr>
            <tr>
                <td>Proxima Vacuna</td>
                <td><i>{{ vacuna.proxima_vacuna }}</i></td>
            </tr>
            <tr>
                <td>Veterinario</td>
                <td><i>{{ vacuna.veterinario }}</i></td>
            </tr>
            </tbody>
        </table>
        <p>

        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-centered">
        <a class="btn btn-primary" href="{% url 'animalchic:list_vacunas' paciente_id %}">Regresar</a>
        <a href="{% url 'animalchic:edit_vacuna' paciente_id vacuna.id %}" class="btn btn-primary">Editar</a>
        <a data-target="#confirm-delete" data-toggle="modal" class="btn btn-danger">Eliminar</a>
    </div>
</div>
<div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Confirmar Eliminacion</h2>
            </div>
            <form method="post">{% csrf_token %}
                <div class="modal-body">
                    ¿Estás seguro que deseas borrar la vacuna "{{ vacuna.descripcion }}"?
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <a href="{% url 'animalchic:delete_vacuna' paciente_id vacuna.id %}" class="btn btn-danger btn-ok">Si</a>
            </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}